name: Deploy

on:
  push:
    paths:
      - '**.py'
      - '**.yml'
      - '**.html'
      - 'zappa_settings.json'
jobs:
  deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: dschep/install-pipenv-action@v1
      - name: Pipenv install
        run: |
          pipenv install
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KEY }}
          AWS_DEFAULT_REGION: ap-east-1
        run: |
          pipenv run zappa update

  deploy_github_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
        working-directory: ./webapp
      - name: Build
        run: yarn build
        working-directory: ./webapp
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webapp/build